Traceback (most recent call last):
  File "debugging.py", line 26, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
